language: node_js

node_js:
  - 0.6

before_script:
  - npm install mocha-phantomjs

script: mocha-phantomjs tests/index.html && mocha-phantomjs tests/index.html#jquery-min && mocha-phantomjs tests/index.html#zepto && mocha-phantomjs tests/index.html#zepto-min